sources:
  - name: minneapolis_old
    database: cities
    schema: public
    tables:
      - name: acs_bg_raw
      - name: acs_tract_raw
      - name: commercial_permits_raw
      - name: fair_market_rents_raw
      - name: residential_permits_raw
      - name: usps_migration
      - name: zip_raw_2000
      - name: zip_raw_2020
  - name: minneapolis
    database: cities
    schema: minneapolis
    tables:
      - name: cb_2010_27_bg_500k
      - name: cb_2010_27_tract_500k
      - name: cb_2013_27_bg_500k
      - name: cb_2013_27_tract_500k
      - name: cb_2014_27_bg_500k
      - name: cb_2014_27_tract_500k
      - name: cb_2015_27_bg_500k
      - name: cb_2015_27_tract_500k
      - name: cb_2016_27_bg_500k
      - name: cb_2016_27_tract_500k
      - name: cb_2017_27_bg_500k
      - name: cb_2017_27_tract_500k
      - name: cb_2018_27_bg_500k
      - name: cb_2018_27_tract_500k
      - name: cb_2019_27_bg_500k
      - name: cb_2019_27_tract_500k
      - name: cb_2020_27_bg_500k
      - name: cb_2020_27_tract_500k
      - name: cb_2021_27_bg_500k
      - name: cb_2021_27_tract_500k
      - name: cb_2022_27_bg_500k
      - name: cb_2022_27_tract_500k
      - name: cb_2023_27_bg_500k
      - name: cb_2023_27_tract_500k
      - name: minneapolis_city_boundary
      - name: minneapolis_neighborhoods
      - name: minneapolis_wards
      - name: parcels2002hennepin
      - name: parcels2003hennepin
      - name: parcels2004hennepin
      - name: parcels2005hennepin
      - name: parcels2006hennepin
      - name: parcels2007hennepin
      - name: parcels2008hennepin
      - name: parcels2009hennepin
      - name: parcels2010hennepin
      - name: parcels2011hennepin
      - name: parcels2012hennepin
      - name: parcels2013hennepin
      - name: parcels2014hennepin
      - name: parcels2015hennepin
      - name: parcels2016hennepin
      - name: parcels2017hennepin
      - name: parcels2018hennepin
      - name: parcels2019hennepin
      - name: parcels2020hennepin
      - name: parcels2021hennepin
      - name: parcels2022hennepin
      - name: parcels2023hennepin

models:
  - name: census_tracts
    columns:
      - name: census_tract_id
        data_tests:
          - unique
          - not_null

  - name: census_block_groups
    columns:
      - name: census_block_group_id
        data_tests:
          - unique
          - not_null
      - name: census_tract_id
        data_tests:
          - relationships:
              to: ref('census_tracts')
              field: census_tract_id

  - name: acs_tract
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - census_tract_id
            - year_
            - name_
    columns:
      - name: census_tract_id
        data_tests:
          - relationships:
              to: ref('census_tracts')
              field: census_tract_id

  - name: acs_block_group
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - census_block_group_id
            - year_
            - name_
    columns:
      - name: census_block_group_id
        data_tests:
          - relationships:
              to: ref('census_block_groups')
              field: census_block_group_id

  - name: segregation_indexes
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - census_tract_id
            - year_
            - distribution
    columns:
      - name: census_tract_id
        data_tests:
          - relationships:
              to: ref('census_tracts')
              field: census_tract_id

  - name: parcels
    columns:
      - name: parcel_id
        data_tests:
          - unique
          - not_null
      - name: zip_code_id
        data_tests:
          - not_null
          - relationships:
              to: ref('zip_codes')
              field: zip_code_id
      - name: census_block_group_id
        data_tests:
          - not_null
          - relationships:
              to: ref('census_block_groups')
              field: census_block_group_id

  - name: parcels_to_census_block_groups
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - parcel_id
            - census_block_group_id
    columns:
      - name: parcel_id
        data_tests:
          - not_null
          - relationships:
              to: ref('parcels')
              field: parcel_id
      - name: census_block_group_id
        data_tests:
          - not_null
          - relationships:
              to: ref('census_block_groups')
              field: census_block_group_id

  - name: parcels_to_zip_codes
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - parcel_id
            - zip_code_id
    columns:
      - name: parcel_id
        data_tests:
          - not_null
          - relationships:
              to: ref('parcels')
              field: parcel_id
      - name: zip_code_id
        data_tests:
          - not_null
          - relationships:
              to: ref('zip_codes')
              field: zip_code_id

  - name: zip_codes_2000
    columns:
      - name: zip_code
        data_tests:
          - not_null
          - unique

  - name: zip_codes_2020
    columns:
      - name: zip_code
        data_tests:
          - not_null
          - unique

  - name: zip_codes
    columns:
      - name: zip_code_id
        data_tests:
          - not_null
          - unique

  - name: usps_migration
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_
            - zip_code_id
            - flow_direction
            - flow_type
    columns:
      - name: zip_code_id
        data_tests:
          - not_null
          - relationships:
              to: ref('zip_codes')
              field: zip_code_id

  - name: commercial_permits
    columns:
      - name: commercial_permit_id
        data_tests:
          - not_null
          - unique
      - name: parcel_id
        data_tests:
          - not_null
          - relationships:
              to: ref('parcels')
              field: parcel_id

  - name: residential_permits
    columns:
      - name: residential_permit_id
        data_tests:
          - not_null
          - unique
      - name: parcel_id
        data_tests:
          - not_null
          - relationships:
              to: ref('parcels')
              field: parcel_id

  - name: neighborhoods
    columns:
      - name: neighborhood_id
        data_tests:
          - not_null
          - unique

  - name: wards
    columns:
      - name: ward_id
        data_tests:
          - not_null
          - unique
